apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: multisourcesingleapp
  namespace: test2
spec:
  subscriptions:
    warehouse: docker2
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/akolacz/argocd-multi-sources
      writeBranch: main
      helm:
        images:
        - image: nginx
          valuesFilePath: argocd-apps/multisourcesingleapp/values.yaml
          key: image.tag
          value: Tag
    argoCDAppUpdates:
    - appName: multisourcesingleapp
      appNamespace: argocd
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: multisourcemultiapp
  namespace: test
spec:
  subscriptions:
    warehouse: docker
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/akolacz/argocd-multi-sources
      writeBranch: main
      helm:
        images:
        - image: nginx
          valuesFilePath: argocd-apps/multisourcemultiapp/nginx_values.yaml
          key: image.tag
          value: Tag
        - image: prometheus
          valuesFilePath: argocd-apps/multisourcemultiapp/prometheus_values.yaml
          key: prometheus.image.tag
          value: Tag
    argoCDAppUpdates:
    - appName: multisourcemultiapp
      appNamespace: argocd
